"""remove uniqueness from name in titles

Revision ID: 1a44a8c0ce7c
Revises: 785f786bccd0
Create Date: 2025-08-01 16:49:31.104576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a44a8c0ce7c'
down_revision: Union[str, Sequence[str], None] = '785f786bccd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='titles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('name'), 'titles', ['name'], unique=True)
    # ### end Alembic commands ###
