"""adding full junction table functionality

Revision ID: 1b03589c02dc
Revises: a154cec22b72
Create Date: 2025-07-29 17:54:22.009341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b03589c02dc'
down_revision: Union[str, Sequence[str], None] = 'a154cec22b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('genres_ibfk_1'), 'genres', type_='foreignkey')
    op.drop_column('genres', 'anime_id')
    op.drop_constraint(op.f('titles_ibfk_1'), 'titles', type_='foreignkey')
    op.drop_column('titles', 'anime_id')
    op.drop_constraint(op.f('topical_themes_ibfk_1'), 'topical_themes', type_='foreignkey')
    op.drop_column('topical_themes', 'anime_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topical_themes', sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('topical_themes_ibfk_1'), 'topical_themes', 'anime', ['anime_id'], ['id'])
    op.add_column('titles', sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('titles_ibfk_1'), 'titles', 'anime', ['anime_id'], ['id'])
    op.add_column('genres', sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('genres_ibfk_1'), 'genres', 'anime', ['anime_id'], ['id'])
    # ### end Alembic commands ###
