"""make some fields unique

Revision ID: 2ab683506a60
Revises: 1b03589c02dc
Create Date: 2025-07-31 14:14:20.959308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab683506a60'
down_revision: Union[str, Sequence[str], None] = '1b03589c02dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'endings', ['title'])
    op.create_unique_constraint(None, 'genres', ['genre'])
    op.create_unique_constraint(None, 'openings', ['title'])
    op.create_unique_constraint(None, 'studios', ['name'])
    op.create_unique_constraint(None, 'titles', ['name'])
    op.create_unique_constraint(None, 'topical_themes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topical_themes', type_='unique')
    op.drop_constraint(None, 'titles', type_='unique')
    op.drop_constraint(None, 'studios', type_='unique')
    op.drop_constraint(None, 'openings', type_='unique')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'endings', type_='unique')
    # ### end Alembic commands ###
