"""testing junction table functionality

Revision ID: 2b0488c25dc1
Revises: c1110dae3d5a
Create Date: 2025-07-29 16:58:54.433045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b0488c25dc1'
down_revision: Union[str, Sequence[str], None] = 'c1110dae3d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('studios_ibfk_1'), 'studios', type_='foreignkey')
    op.drop_column('studios', 'anime_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studios', sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('studios_ibfk_1'), 'studios', 'anime', ['anime_id'], ['id'])
    # ### end Alembic commands ###
