"""remove type field from titles table

Revision ID: 2e2d48c2070f
Revises: c6590edd45c7
Create Date: 2025-08-04 11:53:48.092389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e2d48c2070f'
down_revision: Union[str, Sequence[str], None] = 'c6590edd45c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
