"""rank is optional now

Revision ID: 49886da82a58
Revises: c0239d3ec835
Create Date: 2025-07-24 10:40:09.026297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49886da82a58'
down_revision: Union[str, Sequence[str], None] = 'c0239d3ec835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'rank',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'rank',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
