"""change title to name

Revision ID: 50a83a28537e
Revises: b90eae2eabba
Create Date: 2025-07-29 12:24:48.116753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50a83a28537e'
down_revision: Union[str, Sequence[str], None] = 'b90eae2eabba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('name', sa.String(length=300), nullable=False))
    op.drop_column('title', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('title', mysql.VARCHAR(length=300), nullable=False))
    op.drop_column('title', 'name')
    # ### end Alembic commands ###
