"""making fields in trailer table nullable

Revision ID: 57377a32bd8a
Revises: 7bdc63294208
Create Date: 2025-07-29 12:48:43.902304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57377a32bd8a'
down_revision: Union[str, Sequence[str], None] = '7bdc63294208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trailer', 'url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('trailer', 'embed_url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('trailer', 'youtube_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trailer', 'youtube_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trailer', 'embed_url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trailer', 'url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
