"""fixing profile-user relationship

Revision ID: 5cf7672a756f
Revises: 7ed0a53f33d6
Create Date: 2025-07-22 11:53:15.153163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cf7672a756f'
down_revision: Union[str, Sequence[str], None] = '7ed0a53f33d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_ibfk_1'), 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_ibfk_1'), 'user', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    # ### end Alembic commands ###
