"""change title to name

Revision ID: 785f786bccd0
Revises: 63d3e4ae4252
Create Date: 2025-08-01 16:46:03.830896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '785f786bccd0'
down_revision: Union[str, Sequence[str], None] = '63d3e4ae4252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('name', sa.String(length=300), nullable=False))
    op.drop_column('anime', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('title', mysql.VARCHAR(length=300), nullable=False))
    op.drop_column('anime', 'name')
    # ### end Alembic commands ###
