"""nullable profile_id

Revision ID: 7ed0a53f33d6
Revises: f7e3db1630f5
Create Date: 2025-07-22 11:30:49.321819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ed0a53f33d6'
down_revision: Union[str, Sequence[str], None] = 'f7e3db1630f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
