"""initial migration with tablename fr this time pls

Revision ID: 9cb5990e97da
Revises: dc8cae4ca545
Create Date: 2025-06-19 13:56:18.938127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb5990e97da'
down_revision: Union[str, Sequence[str], None] = 'dc8cae4ca545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
