"""add fk for profile from user again

Revision ID: a80429471096
Revises: cd5dbf835e6b
Create Date: 2025-07-17 17:51:35.364438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a80429471096'
down_revision: Union[str, Sequence[str], None] = 'cd5dbf835e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_user_profile'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_profile'), 'user', 'profile', ['profile_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user', 'profile_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
