"""removing themes tables and adding junction tables instead

Revision ID: a9ab84e1fb14
Revises: 2e2d48c2070f
Create Date: 2025-08-04 14:02:43.625483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9ab84e1fb14'
down_revision: Union[str, Sequence[str], None] = '2e2d48c2070f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_endings',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('endings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endings_id'], ['endings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'endings_id')
    )
    op.create_table('anime_openings',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('openings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['openings_id'], ['openings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'openings_id')
    )
    # Drop foreign key constraints first before dropping the referenced table
    op.drop_constraint(op.f('endings_ibfk_1'), 'endings', type_='foreignkey')
    op.drop_column('endings', 'theme_id')
    op.drop_constraint(op.f('openings_ibfk_1'), 'openings', type_='foreignkey')
    op.drop_column('openings', 'theme_id')
    # Now we can safely drop the themes table
    op.drop_table('themes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openings', sa.Column('theme_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('openings_ibfk_1'), 'openings', 'themes', ['theme_id'], ['id'])
    op.add_column('endings', sa.Column('theme_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('endings_ibfk_1'), 'endings', 'themes', ['theme_id'], ['id'])
    op.create_table('themes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('themes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('anime_openings')
    op.drop_table('anime_endings')
    # ### end Alembic commands ###
