"""adding nullable to player_history field

Revision ID: ad7c7783b3d8
Revises: 1248a6a7264f
Create Date: 2025-07-11 11:15:38.872881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad7c7783b3d8'
down_revision: Union[str, Sequence[str], None] = '1248a6a7264f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'player_history',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'player_history',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###
