"""using forward ref to avoid circular imports and back_populates for bi-directional relationship

Revision ID: b90eae2eabba
Revises: d02bcdb34a0e
Create Date: 2025-07-25 11:45:41.816407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b90eae2eabba'
down_revision: Union[str, Sequence[str], None] = 'd02bcdb34a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'title')
    op.add_column('theme', sa.Column('anime_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'theme', 'anime', ['anime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.drop_column('theme', 'anime_id')
    op.add_column('anime', sa.Column('title', mysql.VARCHAR(length=300), nullable=False))
    # ### end Alembic commands ###
