"""theme_id is nullable now

Revision ID: be686b0af5ef
Revises: 5cf7672a756f
Create Date: 2025-07-23 10:23:42.814506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be686b0af5ef'
down_revision: Union[str, Sequence[str], None] = '5cf7672a756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'theme_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'theme_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
