"""adding junction tables for many to many relationships

Revision ID: c1110dae3d5a
Revises: 8f23a8c6afc5
Create Date: 2025-07-29 16:53:23.210251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1110dae3d5a'
down_revision: Union[str, Sequence[str], None] = '8f23a8c6afc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('anime_studios',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'studio_id')
    )
    op.create_table('anime_titles',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'title_id')
    )
    op.create_table('anime_topical_themes',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('topical_theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['topical_theme_id'], ['topical_themes.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'topical_theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_topical_themes')
    op.drop_table('anime_titles')
    op.drop_table('anime_studios')
    op.drop_table('anime_genres')
    # ### end Alembic commands ###
