"""adding cascade deletion

Revision ID: c6590edd45c7
Revises: 1a44a8c0ce7c
Create Date: 2025-08-04 10:20:27.259160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6590edd45c7'
down_revision: Union[str, Sequence[str], None] = '1a44a8c0ce7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('anime_genres_ibfk_2'), 'anime_genres', type_='foreignkey')
    op.drop_constraint(op.f('anime_genres_ibfk_1'), 'anime_genres', type_='foreignkey')
    op.create_foreign_key(None, 'anime_genres', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anime_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('anime_studios_ibfk_2'), 'anime_studios', type_='foreignkey')
    op.drop_constraint(op.f('anime_studios_ibfk_1'), 'anime_studios', type_='foreignkey')
    op.create_foreign_key(None, 'anime_studios', 'studios', ['studio_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anime_studios', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('anime_titles_ibfk_2'), 'anime_titles', type_='foreignkey')
    op.drop_constraint(op.f('anime_titles_ibfk_1'), 'anime_titles', type_='foreignkey')
    op.create_foreign_key(None, 'anime_titles', 'titles', ['title_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anime_titles', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('anime_topical_themes_ibfk_2'), 'anime_topical_themes', type_='foreignkey')
    op.drop_constraint(op.f('anime_topical_themes_ibfk_1'), 'anime_topical_themes', type_='foreignkey')
    op.create_foreign_key(None, 'anime_topical_themes', 'topical_themes', ['topical_theme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anime_topical_themes', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anime_topical_themes', type_='foreignkey')
    op.drop_constraint(None, 'anime_topical_themes', type_='foreignkey')
    op.create_foreign_key(op.f('anime_topical_themes_ibfk_1'), 'anime_topical_themes', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key(op.f('anime_topical_themes_ibfk_2'), 'anime_topical_themes', 'topical_themes', ['topical_theme_id'], ['id'])
    op.drop_constraint(None, 'anime_titles', type_='foreignkey')
    op.drop_constraint(None, 'anime_titles', type_='foreignkey')
    op.create_foreign_key(op.f('anime_titles_ibfk_1'), 'anime_titles', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key(op.f('anime_titles_ibfk_2'), 'anime_titles', 'titles', ['title_id'], ['id'])
    op.drop_constraint(None, 'anime_studios', type_='foreignkey')
    op.drop_constraint(None, 'anime_studios', type_='foreignkey')
    op.create_foreign_key(op.f('anime_studios_ibfk_1'), 'anime_studios', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key(op.f('anime_studios_ibfk_2'), 'anime_studios', 'studios', ['studio_id'], ['id'])
    op.drop_constraint(None, 'anime_genres', type_='foreignkey')
    op.drop_constraint(None, 'anime_genres', type_='foreignkey')
    op.create_foreign_key(op.f('anime_genres_ibfk_1'), 'anime_genres', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key(op.f('anime_genres_ibfk_2'), 'anime_genres', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
