"""new topical_themes table

Revision ID: cfe36c3bbcea
Revises: ac6ff989a525
Create Date: 2025-07-23 16:38:16.032364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe36c3bbcea'
down_revision: Union[str, Sequence[str], None] = 'ac6ff989a525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topical_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('anime', sa.Column('topical_theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anime', 'topical_themes', ['topical_theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anime', type_='foreignkey')
    op.drop_column('anime', 'topical_theme_id')
    op.drop_table('topical_themes')
    # ### end Alembic commands ###
