"""remove unique constraint from rank

Revision ID: d02bcdb34a0e
Revises: 49886da82a58
Create Date: 2025-07-24 12:16:18.607965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02bcdb34a0e'
down_revision: Union[str, Sequence[str], None] = '49886da82a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('rank'), table_name='anime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('rank'), 'anime', ['rank'], unique=True)
    # ### end Alembic commands ###
