"""changing naming to correctly represent entities and collections

Revision ID: fdcab630a4b1
Revises: 50a83a28537e
Create Date: 2025-07-29 12:29:58.641482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcab630a4b1'
down_revision: Union[str, Sequence[str], None] = '50a83a28537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('title', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'title')
    # ### end Alembic commands ###
